// Maps the available categories to serve and be in sync with frontend queries
// https://runescape.wiki/w/Application_programming_interface#Catalogue

export default [
  { id: 0, data: 'Miscellaneous' },
  { id: 1, data: 'Ammo' },
  { id: 2, data: 'Arrows' },
  { id: 3, data: 'Bolts' },
  { id: 4, data: 'Construction materials' },
  { id: 5, data: 'Construction products' },
  { id: 6, data: 'Cooking ingredients' },
  { id: 7, data: 'Costumes' },
  { id: 8, data: 'Crafting materials' },
  { id: 9, data: 'Familiars' },
  { id: 10, data: 'Farming produce' },
  { id: 11, data: 'Fletching materials' },
  { id: 12, data: 'Food and Drink' },
  { id: 13, data: 'Herblore materials' },
  { id: 14, data: 'Hunting equipment' },
  { id: 15, data: 'Hunting Produce' },
  { id: 16, data: 'Jewellery' },
  { id: 17, data: 'Mage armour' },
  { id: 18, data: 'Mage weapons' },
  { id: 19, data: 'Melee armour - low level' },
  { id: 20, data: 'Melee armour - mid level' },
  { id: 21, data: 'Melee armour - high level' },
  { id: 22, data: 'Melee weapons - low level' },
  { id: 23, data: 'Melee weapons - mid level' },
  { id: 24, data: 'Melee weapons - high level' },
  { id: 25, data: 'Mining and Smithing' },
  { id: 26, data: 'Potions' },
  { id: 27, data: 'Prayer armour' },
  { id: 28, data: 'Prayer materials' },
  { id: 29, data: 'Range armour' },
  { id: 30, data: 'Range weapons' },
  { id: 31, data: 'Runecrafting' },
  { id: 32, data: 'Runes, Spells and Teleports' },
  { id: 33, data: 'Seeds' },
  { id: 34, data: 'Summoning scrolls' },
  { id: 35, data: 'Tools and containers' },
  { id: 36, data: 'Woodcutting product' },
  { id: 37, data: 'Pocket items' },
  { id: 38, data: 'Stone spirits' },
  { id: 39, data: 'Salvage' },
  { id: 40, data: 'Firemaking products' },
  { id: 41, data: 'Archaeology materials ' },
];
